# Generated by Django 5.1.3 on 2024-12-25 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Backorders",
            fields=[
                (
                    "backorder_id",
                    models.AutoField(
                        db_column="BackOrderID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="Title", max_length=255)),
                ("publisher", models.CharField(db_column="Publisher", max_length=100)),
                ("quantity", models.IntegerField(db_column="Quantity")),
                ("registration_date", models.DateField(db_column="RegistrationDate")),
                ("notified", models.BooleanField(db_column="Notified", default=False)),
            ],
            options={
                "db_table": "BackOrders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "book_id",
                    models.IntegerField(
                        db_column="BookID", primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(db_column="Title", max_length=255)),
                ("publisher", models.CharField(db_column="Publisher", max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=2, max_digits=10
                    ),
                ),
                ("stock_quantity", models.IntegerField(db_column="StockQuantity")),
                (
                    "stock_place",
                    models.CharField(
                        blank=True, db_column="StockPlace", max_length=255, null=True
                    ),
                ),
                ("author1st", models.CharField(db_column="Author1st", max_length=100)),
                (
                    "author2nd",
                    models.CharField(
                        blank=True, db_column="Author2nd", max_length=100, null=True
                    ),
                ),
                (
                    "author3rd",
                    models.CharField(
                        blank=True, db_column="Author3rd", max_length=100, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Books",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Booksuppliers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "BookSuppliers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "customer_id",
                    models.AutoField(
                        db_column="CustomerID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=100)),
                ("password", models.CharField(db_column="Password", max_length=255)),
                (
                    "address",
                    models.CharField(
                        blank=True, db_column="Address", max_length=255, null=True
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(
                        db_column="AccountBalance",
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                    ),
                ),
                (
                    "credit_level",
                    models.IntegerField(db_column="CreditLevel", default=1),
                ),
                (
                    "cumulative_amount",
                    models.DecimalField(
                        db_column="CumulativeAmount",
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "db_table": "Customers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orderdetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(db_column="Quantity")),
                (
                    "price",
                    models.DecimalField(
                        db_column="Price", decimal_places=2, default=0.0, max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "OrderDetails",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "order_id",
                    models.AutoField(
                        db_column="OrderID", primary_key=True, serialize=False
                    ),
                ),
                ("order_date", models.DateField(db_column="OrderDate")),
                (
                    "total_amount",
                    models.DecimalField(
                        db_column="TotalAmount",
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                    ),
                ),
                (
                    "shipping_address",
                    models.CharField(db_column="ShippingAddress", max_length=255),
                ),
                (
                    "order_status",
                    models.CharField(
                        db_column="OrderStatus", default="unpayed", max_length=50
                    ),
                ),
            ],
            options={
                "db_table": "Orders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Purchaseorders",
            fields=[
                (
                    "purchase_order_id",
                    models.AutoField(
                        db_column="PurchaseOrderID", primary_key=True, serialize=False
                    ),
                ),
                ("order_date", models.DateField(db_column="OrderDate")),
                (
                    "status",
                    models.CharField(db_column="Status", default="0", max_length=50),
                ),
            ],
            options={
                "db_table": "PurchaseOrders",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Supplierbookinfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "supply_price",
                    models.DecimalField(
                        db_column="SupplyPrice", decimal_places=2, max_digits=10
                    ),
                ),
            ],
            options={
                "db_table": "SupplierBookInfo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Suppliers",
            fields=[
                (
                    "supplier_id",
                    models.IntegerField(
                        db_column="SupplierID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(db_column="SupplierName", max_length=50),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, db_column="Phone", max_length=11, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Suppliers",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bookkeywords",
            fields=[
                (
                    "book_id",
                    models.ForeignKey(
                        db_column="BookID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="bookstore.books",
                    ),
                ),
                (
                    "keyword_name",
                    models.CharField(db_column="KeywordName", max_length=50),
                ),
            ],
            options={
                "db_table": "BookKeywords",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "book_id",
                    models.ForeignKey(
                        db_column="BookID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="bookstore.books",
                    ),
                ),
                ("series_id", models.SmallIntegerField(db_column="SeriesID")),
            ],
            options={
                "db_table": "Series",
                "managed": False,
            },
        ),
    ]
